### PR TITLE
Add raw property to credential parser output

### PR DESCRIPTION
**Pull request by mattjdev**
This will fix [this API issue](https://github.com/activeprospect/leadconduit-api/issues/216)

### CODE REVIEW

**Comment by alexkwolfe** [comment]
I'm fairly sure this is by design. If we include the `raw` property, then we'll be saving the original value of the credential. The whole point of this field is to provide a masked value. If someone designates a field as a credential, we want to store the masked value only (the value with each character replaced with an asterisk).

**Comment by mattjdev** [comment]
Hah! Good point..
So the raw value of `supercalifragilisticexpialidocious` should be: `********************************************`, or should we just have a fixed number like 10 `*`s? The other problem is that for examples we would be 'telling' people to input a bunch of stars... (unless they are all smart enough to get it..)

**Comment by alexkwolfe** [comment]
IMO, there's no point in having the raw value. Having it seems to indicate that the raw value was all asterisks. And it would just be a duplication of what's already in normal, in theory. 

We could solve this in calls to `/meta` by returning the `normal` value in the `raw` property for the purposes of the API response.

**Comment by mattjdev** [comment]
Fixed with [this API PR](https://github.com/activeprospect/leadconduit-api/pull/235)

**Pull request closed without merging**
