### PR TITLE
Refactor email parsing

### LINKED ISSUE #100: Add "free" and "disposable" properties to email type
For B2B lead buyers it might make sense to filter out leads with a "free"  (gmail.com) or "disposable" (disposableaddress.com) email address. In other circumstances, it might make sense to limit calls to an enhancement service (Clearbit company lookup) for leads with free or disposable addresses because the service only works with corporate domains.

Take a look at the [freemail package](https://github.com/willwhite/freemail), which provides a database of free and disposable addresses.

### PR DESCRIPTION
**Pull request by chasingSublimity**
closes #100

### CODE REVIEW

**Comment by alexkwolfe** [comment]
I'm concerned about the performance of freemail. It does an `indexOf` on a huge array of domains in order to determine if it's a free account. This issue was addressed in a PR, but it hasn't yet been merged. 

https://github.com/willwhite/freemail/pull/38

**Comment by chasingSublimity** [comment]
Heard. We could always fork the PR author's branch, if it is deemed sufficiently performant. The tests would need to be refactored/beefed-up, but I don't think that would take very long.

The original project looks dead, unfortunately. I'm looking for other npm packages, but none appear to quite fit our use case.

**Comment by alexkwolfe** [comment]
I'm cool if we fork it. The performance improvement shown in the PR seems worth it...

**Comment by chasingSublimity** [comment]
@alexkwolfe something like this?

```
function handleFreemailValidation(email) {
  if (typeof email !== 'string') throw new TypeError('email must be a string');
  var split = email.split('@');
  var domain = getDomain(split[1] || split[0]);
  return {
    isFree: !!(domain && free[domain]),
    isDisposable: !!(domain && disposable[domain])
  };
}
```

**Pull request merged**
